### ISSUE TITLE
Guide is out of date with DLU main

### ISSUE THREAD

**Issue by EmosewaMC** [maxdelayer/DLUQuickstart#2]
Just letting you know of the following changes that drastically simplify setup and management of a DLU server:
- no linking, copying or moving of client files is needed.  You can even put the client in a readonly directory as we dont need to extract or write anything to the client path.  Simply add the client_path to sharedconfig.ini and the server will figure out where the files are based on that.  We also now support packed and unpacked clients, so it is more advised to use a packed client due to the smaller install size compared to an unpacked client, if the server just needs files.
- The server now converts the cdclient.fdb to CDServer.sqlite and puts the resulting sqlite file in `resServer` so you only need to link the file that is put there when the server starts.
- Unless im mistaken, there is no need to run 0_initial.sql as the server will take care of that for you on initial boot.
- MasterServer can now be run from anywhere.  No need to worry about being in build specifically anymore.
- Stopping MasterServer with SIGKILL is not recommended as this will _not_ save any player data since the last save and will cause issues down the line.  a more graceful shutdown through SIGINT or SIGTERM is advisable.
- The server on build extracts the navmeshes automatically so that step is not needed anymore as well

Hope this helps simplify your scripts!

**Comment by maxdelayer** [comment]
Good to know, thanks for making me aware of this and giving the concise summary - I don't stay super tuned in to what new commits are out there. The server handling client files on its own is huge! I'll try to update this soon and make sure it's compatible again.

Are there any other big changes to server installation, administration, and/or configuration that are in the works or planned down the line?

**Comment by EmosewaMC** [comment]
The main server does not distribute client files - rather once you give us the path to the client in sharedconfig, we will take care of finding the files on our own from that path on the disk.  you still need to source the client, but once you have it setup is very simple
Unfortunately due to legal reasons we cannot distribute client files :(
Only big change down the line would be an ORM to allow us to have solo players not have a need to install mysql and make a database in sqlite instead for smaller, non-scaling instances

**Comment by maxdelayer** [comment]
Yeah, of course, I never implied it distributes client files - I understand those constraints. Just wanted to say the fact that the server can handle configuring itself for them without requiring so much manual intervention is an awesome update. That removes a lot of the tedium and potential for human error during installation that lead me to publishing my own automations in the first place. Very nice.

Anyways, that's interesting, good to know. Thanks for the heads up!

**Comment by EmosewaMC** [comment]
Ah now reading again yea you didnt really say it distributes client files - sorry!

**Comment by maxdelayer** [comment]
`servermanager.sh` takes into account all of these changes now, closing issue
